Add test for bug #75140
phpcommunity/phptestfest-php-src pull request #1
Opened 2017-09-07 00:35 UTC by johnkary

Contributing as part of PHP Test Fest for Kansas City PHP User Group
🎉 

Bug is related to [`session.sid_length`](http://php.net/manual/en/session.configuration.php#ini.session.sid-length) which was introduced in PHP 7.1.0, so this PR is against 7.1 branch.

If format of this commit or the PHPT file should be different let me know!

Thanks,
John Kary
Co-Organizer, Kansas City PHP User Group

2017-09-08 16:45 UTC, ericpoe commented
Can someone kick the tires of this? It looks like travis-ci had a hiccup while running the non-debug version of the build.

2017-09-08 17:45 UTC, ramsey commented
I just restarted that build. Hopefully, it completes properly this time.

2019-02-08 18:16 UTC, carusogabriel requested changes

2019-02-08 18:16 UTC, carusogabriel commented on ext/session/tests/bug75140.phpt
> +--XFAIL--
We won't accept `XFAIL` tests :confused:

2019-02-11 20:46 UTC, petk commented
Hello, thank you for the pull request. This has been also opened at https://github.com/php/php-src/pull/3802 and it seems that the only proper way here is to fix the mentioned bug instead. XFAIL tests aren't being added in the php-src anymore unfortunately.

2019-02-11 20:46 UTC, closed without merging