Add test showing bug #65601
phpcommunity/phptestfest-php-src pull request #10
Opened 2017-09-14 03:54 UTC by ericpoe

The bug, as described, is a bit of a red herring at this time. It appears that `SplFileObject::current()` advances the iterator without calling `SplFileObject::next()`. This PR shows that.

2017-10-25 07:56 UTC, krakjoe approved these changes

2019-02-09 15:13 UTC, carusogabriel requested changes

2019-02-09 15:13 UTC, carusogabriel commented on ext/spl/tests/bug65601.phpt
> +--XFAIL--
We won't accept `XFAIL` tests :confused:

2019-02-11 21:01 UTC, petk commented
Hello, thank you for the pull request. The XFAIL tests for the PHP-7.4 and master branches should instead go one step further and try to fix the bug if possible. The XFAIL tests are not being merged to the php-src repository anymore. Thanks and sorry for inconvenience.

2019-02-11 21:01 UTC, closed without merging