Prove bug #68682
phpcommunity/phptestfest-php-src pull request #13
Opened 2017-09-18 02:05 UTC by ericpoe

Prove that [bug #68682](https://bugs.php.net/bug.php?id=68682) exists.

Show that non-public members are not iterated by `RecursiveIteratorIterator`

User Group: Kansas City PHP

2017-10-25 07:55 UTC, krakjoe approved these changes

2019-02-09 15:25 UTC, carusogabriel requested changes

2019-02-09 15:25 UTC, carusogabriel commented on ext/spl/tests/bug68682.phpt
> +--XFAIL--
We won't accept `XFAIL` tests :confused:

2019-02-11 20:59 UTC, petk commented
Hello, thank you for the pull request. The XFAIL tests for the PHP-7.4 and master branches should instead go one step further and try to fix the bug if possible. The XFAIL tests are being merged to the php-src repository anymore. Thanks and sorry for inconvenience.

2019-02-11 20:59 UTC, closed without merging