Add test for DatePeriod::__set_state
phpcommunity/phptestfest-php-src pull request #155
Opened 2018-06-01 19:05 UTC by omerida

2019-02-08 23:13 UTC, carusogabriel requested changes

2019-02-08 23:13 UTC, carusogabriel commented on ext/date/tests/date_period_set_state_error.phpt
> +Warning: DatePeriod::__set_state() expects parameter 1 to be array, %s given in %s on line %d
We won't accept ZPP Failures tests :confused:

2019-02-09 16:18 UTC, omerida commented
Is this documented somewhere? There should be a way to exclude these lines from coverage tests if you don’t want tests for them.

Sent from my iPhone

> On Feb 8, 2019, at 6:13 PM, Gabriel Caruso <notifications@github.com> wrote:
> 
> @carusogabriel requested changes on this pull request.
> 
> In ext/date/tests/date_period_set_state_error.phpt:
> 
> > @@ -0,0 +1,13 @@
> +--TEST--
> +Testing passing integer to DatePeriod::__set_state should fail.
> +--CREDITS--
> +Oscar Merida <oscar@musketeers.me>
> +#phptestfest2017
> +--FILE--
> +<?php
> +$dp = new \DatePeriod('R4/2012-07-01T00:00:00Z/P7D');
> +$dp->__set_state(1);
> +?>
> +--EXPECTF--
> +Warning: DatePeriod::__set_state() expects parameter 1 to be array, %s given in %s on line %d
> We won't accept ZPP Failures tests 😕
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-02-09 16:29 UTC, carusogabriel commented
@omerida Please take a look at https://externals.io/message/103886.

2019-02-09 16:45 UTC, petk commented
Every time the pull request here can't get merged a kitten dies and breaks mergers heart, but I also am not sure what other way to do in the time of PHP 7.4... Let not this stop you from adding a new test for something else or with different approach. I'll check what we can do with these if anything...

2019-02-17 18:58 UTC, petk commented
Hello, thank you for the pull request. As mentioned above, the ZPP tests aren't being merge to the upstream anymore because they test redundant things. See this discussion for more info at https://externals.io/message/103886

Closing this one as resolved. 👍

I'll also add instructions to qa.php.net site which is basically the main source of information about PHP tests...

2019-02-17 18:58 UTC, closed without merging