Adds test for Bug 63663
phpcommunity/phptestfest-php-src pull request #17
Opened 2017-09-21 19:03 UTC by heiglandreas

This test currently verifies that non ASCII-Characters break the wordcount of str_word_count

This is the first test from the PHPUGFFM created during the testfest in 2017

2017-10-25 07:52 UTC, krakjoe approved these changes

2019-02-08 18:21 UTC, carusogabriel approved these changes

2019-02-08 18:21 UTC, carusogabriel commented on tests/strings/bug63663.phpt
> +--XFAIL--
We won't merge `XFAIL` tests :confused:

2019-02-08 18:22 UTC, carusogabriel requested changes
We won't merge `XFAIL` tests :confused:

2019-02-11 20:54 UTC, petk commented
Hello, thank you for the pull request. Unfortunately, the XFAIL tests are not being merged in the php-src anymore. These tests should go one step further and instead try to fix the bug if possible.

2019-02-11 20:54 UTC, closed without merging