adds test for bug 70110
phpcommunity/phptestfest-php-src pull request #18
Opened 2017-09-21 19:27 UTC by heiglandreas

This tests that certain regexes actually fail at the moment. For more information have a look at https://bugs.php.net/bug.php?id=70110

This is the second PR of the PHPUGFFM for the PHPTestFest 2017

2017-09-23 03:23 UTC, ericpoe commented
Can someone restart the tests on this PR? It looks like one Travis config worked and the other didn't.

2017-09-23 05:05 UTC, ramsey commented
I just restarted the job.

2017-10-25 07:51 UTC, krakjoe approved these changes

2019-02-08 18:22 UTC, carusogabriel requested changes

2019-02-08 18:22 UTC, carusogabriel commented on ext/pcre/tests/bug70110.phpt
> +--XFAIL--
We won't merge `XFAIL` tests :confused:

2019-02-11 20:54 UTC, petk commented
Hello, thank you for the pull request. Unfortunately, the XFAIL tests are not being merged in the php-src anymore. These tests should go one step further and instead try to fix the bug if possible.

2019-02-11 20:54 UTC, closed without merging