Add test for error_clear_last with invalid arguments
phpcommunity/phptestfest-php-src pull request #19
Opened 2017-09-22 02:43 UTC by minond

Adds coverage for when `error_clear_last` is called with an argument, which it does not expect, and is supposed to immediately return and log a warning.

Doing this as part of UPHPU's 2017 TestFest.

2017-10-25 07:49 UTC, krakjoe approved these changes
This is related to, but not directly testing zpp ... it feels acceptable since the comparison to the return value of related function is important ...

2019-02-08 18:23 UTC, carusogabriel requested changes

2019-02-08 18:23 UTC, carusogabriel commented on ext/standard/tests/general_functions/error_clear_last_error.phpt
> +Warning: error_clear_last() expects exactly 0 parameters, 1 given in %s on line %d
We won't merge ZPP failure tests :confused:

2019-02-09 15:32 UTC, carusogabriel commented
This test basically tests ZPP failures and we do not accept it anymore.

2019-02-09 15:32 UTC, closed without merging