Add test for bug #75135
phpcommunity/phptestfest-php-src pull request #2
Opened 2017-09-07 01:08 UTC by ericpoe

This tests that the bug reported in #75135 is actually a bug.

2017-09-07 14:34 UTC, ramsey commented
I believe you need to add the `--XFAIL--` section to this test: https://qa.php.net/phpt_details.php#xfail_section

2017-10-27 07:34 UTC, krakjoe approved these changes

2019-02-08 18:17 UTC, carusogabriel requested changes

2019-02-08 18:17 UTC, carusogabriel commented on ext/spl/tests/bug75135.phpt
> +--XFAIL--
We won't accept `XFAIL` tests :confused:

2019-02-11 20:48 UTC, petk commented
Hello, thank you for the pull request. It seems that the only proper way here is to fix the mentioned bug instead. XFAIL tests aren't being added in the php-src anymore unfortunately.

2019-02-11 20:48 UTC, closed without merging