test warning for nul args on register_shutdown_functions
phpcommunity/phptestfest-php-src pull request #21
Opened 2017-09-22 03:27 UTC by mahelious

test register_shutdown_function() throws a warning when called with no args

code coverage on http://gcov.php.net/PHP_7_0/lcov_html/ext/standard/basic_functions.c.gcov.php::5038

2017-09-23 01:33 UTC, ericpoe commented
Hi @mahelious, which user group are you with? You will want to tag this PR with "User Group: Name of Group" (ex: https://github.com/phpcommunity/phptestfest-php-src/pull/14)

2017-09-23 01:39 UTC, mahelious commented
Updated PR with user group. Thank you @ericpoe

2017-10-25 07:45 UTC, krakjoe approved these changes
This looks like a ZPP test, but isn't ... for some reason that function goes about things in a difficult way without calling zpp, but does call related apis and uses WRONG_PARAM_COUNT convention ...

2019-02-08 18:24 UTC, carusogabriel requested changes

2019-02-08 18:24 UTC, carusogabriel commented on ext/standard/tests/reg_shutdown_func.phpt
> +Warning: Wrong parameter count for register_shutdown_function() in %s on line %d
We won't accept ZPP failure tests :confused:

2019-02-09 00:44 UTC, carusogabriel commented
This test basically tests ZPP failures, and we don't accept this tests anymore.

2019-02-09 00:44 UTC, closed without merging