Added basic tests for http_response_code
phpcommunity/phptestfest-php-src pull request #23
Opened 2017-09-22 16:07 UTC by mbniebergall

Added basic tests for `http_response_code` since there weren't any yet.

UPHPU (Utah PHP User Group) for PHP TestFest 2017

2017-10-25 07:42 UTC, krakjoe commented on ext/standard/tests/http/http_response_code_basic.phpt
> +Warning: http_response_code() expects parameter 1 to be integer, string given in %s on line %d
This is an unnecessary test of ZPP.

2017-10-25 07:42 UTC, krakjoe requested changes
ZPP

2017-10-26 17:39 UTC, mbniebergall commented on ext/standard/tests/http/http_response_code_basic.phpt
> +Warning: http_response_code() expects parameter 1 to be integer, string given in %s on line %d
Removed ZPP

2019-02-08 18:25 UTC, carusogabriel requested changes
This is already been tested via https://github.com/php/php-src/blob/master/ext/standard/tests/general_functions/http_response_code.phpt

2019-02-09 00:45 UTC, carusogabriel commented
Closing as there's already a test for that upstream.

2019-02-09 00:45 UTC, closed without merging