Show that bug #60762 still exists
phpcommunity/phptestfest-php-src pull request #27
Opened 2017-09-23 02:56 UTC by ericpoe

IteratorIterator is supposed to be an outer-iterator for anything that implements `\Traversable`. In other words, this provides `next()`, `current()`, `rewind()`, `key()`, and `valid()` for the traversable object. However, when an IteratorIterator is wrapped around `DOMNodeList` (which implements `\Traversable`), the innerIterator is no longer traversable via `foreach`.

User Group: Kansas City PHP

2017-10-25 07:34 UTC, krakjoe approved these changes

2019-02-08 18:27 UTC, carusogabriel requested changes

2019-02-08 18:27 UTC, carusogabriel commented on ext/spl/tests/bug60762.phpt
> +--XFAIL--
We won't accept `XFAIL` tests :confused:

2019-02-11 20:52 UTC, petk commented
Hello, thank you for the pull request. It seems that XFAIL tests are not being accepted in the php-src repository anymore. However, a better way here is to try to fix the mentioned bug instead.

2019-02-11 20:52 UTC, closed without merging