Prove the existence of bug #48375
phpcommunity/phptestfest-php-src pull request #3
Opened 2017-09-07 17:10 UTC by ericpoe

This PR proves the existence of [bug #48375](https://bugs.php.net/bug.php?id=48375).

This bug causes a timeout, so I have set the time limit to 5 seconds. I don't want to add too much time to an already lengthy test process!

2017-09-07 19:57 UTC, SammyK commented
Nice! Since it's a slow test you'll want to add a `--SKIPIF--` section that will skip it if slow tests are turned off: https://github.com/php/php-src/blob/6053987bc27e8dede37f437193a5cad448f99bce/ext/standard/tests/network/gethostbyname_basic001.phpt#L7

2017-10-27 07:35 UTC, krakjoe approved these changes

2019-02-08 18:17 UTC, carusogabriel requested changes

2019-02-08 18:17 UTC, carusogabriel commented on ext/spl/tests/bug48375.phpt
> +--XFAIL--
We won't merge `XFAIL` tests :confused:

2019-02-11 20:49 UTC, petk commented
Hello, thank you for the pull request. It seems that the only proper way here is to fix the mentioned bug instead. XFAIL tests aren't being added in the php-src anymore unfortunately.

2019-02-11 20:49 UTC, closed without merging