Provide alternative tests for Bug #36759
phpcommunity/phptestfest-php-src pull request #31
Opened 2017-10-02 05:02 UTC by ericpoe

This bug already has a passing test; however, in the comments for [bug #36759](https://bugs.php.net/bug.php?id=36759#1300676697) these two variations were mentioned as failing in 2011. Good news! One variation now passes! Unfortunately, the other variation still fails.

2017-10-02 05:03 UTC, ericpoe commented
A third variation is mentioned, but I really don't know how to test it based on the information provided. Any ideas?

2019-02-09 02:03 UTC, carusogabriel requested changes

2019-02-09 02:03 UTC, carusogabriel commented on Zend/tests/bug36759_variation1.phpt
> +--XFAIL--
We won't accept `XFAIL` tests.

2019-02-11 21:02 UTC, petk commented
Hello, thank you for the pull request. The XFAIL tests for the PHP-7.4 and master branches should instead go one step further and try to fix the bug if possible. The XFAIL tests are not being merged to the php-src repository anymore. Thanks and sorry for inconvenience.

2019-02-11 21:02 UTC, closed without merging