Added tests for xml_parser_set_option
phpcommunity/phptestfest-php-src pull request #71
Opened 2017-10-27 15:46 UTC by mbniebergall

Added tests when setting the skip whitespace option for xml_parser_set_option and tests when setting the target encoding with an invalid value, which triggers the "Unsupported target encoding..." error.

Tests http://gcov.php.net/PHP_7_2/lcov_html/ext/xml/xml.c.gcov.php lines 1604-1606 and 1612-1613.

Credit: PHP TestFest 2017 - Utah PHP User Group (UPHPU)

2017-10-27 16:07 UTC, krakjoe requested changes
I think just one call to set skip white option is enough to cover the line, it would appear the two lines create identical coverage.

Similarly, just one call to set the target encoding to something invalid will create the same coverage.

2017-11-06 15:55 UTC, mbniebergall commented
@krakjoe I removed the doubled up testing lines per your suggestion.

2019-02-09 16:28 UTC, carusogabriel approved these changes

2019-02-10 18:54 UTC, petk commented
Applied via https://github.com/php/php-src/commit/e727facd4766d8eb42245f2ea3fb9a25ccf4fa5b in the php-src repository to PHP-7.4 and master branches. Thank you @mbniebergall for the pull request and @carusogabriel, @krakjoe for the review.

2019-02-10 18:54 UTC, closed without merging