Prove bug#34217 related to array_unique function
phpcommunity/phptestfest-php-src pull request #74
Opened 2017-10-29 11:53 UTC by yuklia

https://bugs.php.net/bug.php?id=34217

2017-10-30 07:00 UTC, krakjoe approved these changes

2019-02-09 01:17 UTC, carusogabriel requested changes

2019-02-09 01:17 UTC, carusogabriel commented on ext/standard/tests/array/bug34217.phpt
> +--XFAIL--
We won't accept `XFAIL` tests :confused:

2019-02-09 01:23 UTC, carusogabriel commented
Actually, this was fixed. See [#34217](https://bugs.php.net/bug.php?id=34217). I couldn't find a test for that, so would be nice to have :)

2019-03-30 17:50 UTC, petk commented
Thank you for the pull request. Since we can't know the status of this pr anymore, I'll be merging the rest of the contributions in a single commit... More info on this soon.

2019-03-30 17:50 UTC, closed without merging