Prove bug #65672. Related to DatePeriod
phpcommunity/phptestfest-php-src pull request #77
Opened 2017-10-29 15:19 UTC by yuklia

Prove that bug [#65672]( https://bugs.php.net/bug.php?id=65672) exists.

(Not Existed Yet) User Group: [ Kharkiv PHP (https://github.com/phpcommunity/phptestfest.org/pull/70)

2017-10-30 07:04 UTC, krakjoe approved these changes

2019-02-09 01:12 UTC, carusogabriel requested changes

2019-02-09 01:12 UTC, carusogabriel commented on ext/date/tests/bug65672.phpt
> +--XFAIL--
We won't accept `XFAIL` tests :confused:

2019-02-11 21:03 UTC, petk commented
Hello, thank you for the pull request. The XFAIL tests for the PHP-7.4 and master branches should instead go one step further and try to fix the bug if possible. The XFAIL tests are not being merged to the php-src repository anymore. Thanks and sorry for inconvenience.

2019-02-11 21:03 UTC, closed without merging