Show that bug49607 is still valid
phpcommunity/phptestfest-php-src pull request #8
Opened 2017-09-13 02:48 UTC by ericpoe

This bug shows that [#49607](http://php.net/manual/en/class.cachingiterator.php) is still a valid bug.

One would expect the `CachingIterator` to show the same output in a `foreach` is the iterator it is caching. This bug shows that is not the case when it comes to a `DirectoryIterator`

2017-10-25 07:57 UTC, krakjoe approved these changes

2019-02-09 15:12 UTC, carusogabriel requested changes

2019-02-09 15:12 UTC, carusogabriel commented on ext/spl/tests/bug49607.phpt
> +--XFAIL--
We won't accept `XFAIL` tests :confused:

2019-02-11 21:01 UTC, petk commented
Hello, thank you for the pull request. The XFAIL tests for the PHP-7.4 and master branches should instead go one step further and try to fix the bug if possible. The XFAIL tests are not being merged to the php-src repository anymore. Thanks and sorry for inconvenience.

2019-02-11 21:01 UTC, closed without merging