Add test for bug 75449
phpcommunity/phptestfest-php-src pull request #80
Opened 2017-10-31 04:12 UTC by ericpoe

[Bug #75449](https://bugs.php.net/bug.php?id=75449) is more of an expectation than a bug. Yet, it seems a very reasonable, bug-like, expectation. :)

User Group: Kansas City PHP

2017-10-31 05:08 UTC, krakjoe commented
Well ... this is a horrible bug in the object model ... one that I would hope can be fixed ...

2017-10-31 05:08 UTC, krakjoe approved these changes

2017-11-02 00:41 UTC, ericpoe commented
Any ideas why Travis fails this test?

2017-11-02 06:01 UTC, krakjoe commented
The EXPECTF section looks like what we expect when zend is fixed, the output we get now is bound to be stupid ... 

I can see why this bug occurs, but not exactly sure what to do about it ... 

Anyway, it doesn't fail; It's expected to fail with surprising output and does ... the build has gone red on travis for other unrelated reasons ...

2019-02-09 01:11 UTC, carusogabriel requested changes

2019-02-09 01:11 UTC, carusogabriel commented on Zend/tests/traits/bug75449.phpt
> +--XFAIL--
We won't accept `XFAIL` tests :confused:

2019-02-11 21:04 UTC, petk commented
Hello, thank you for the pull request. The XFAIL tests for the PHP-7.4 and master branches should instead go one step further and try to fix the bug if possible. The XFAIL tests are not being merged to the php-src repository anymore. Thanks and sorry for inconvenience.

2019-02-11 21:04 UTC, closed without merging