Provide test for bug #68004
phpcommunity/phptestfest-php-src pull request #9
Opened 2017-09-14 02:40 UTC by ericpoe

Provide a test for bug [#68004](https://bugs.php.net/bug.php?id=68004)

One interesting aspect of this test is that it creates a tiny temp file in memory (when smaller than 2MB) that gets destroyed when this test gets destroyed. That should be faster than creating a file on the filesystem and then going through a cleanup script when the test is finished. `SplTempFileObject()` FTW!

KCPHPUG TestFest 2017

2017-10-25 07:56 UTC, krakjoe approved these changes

2019-02-09 15:13 UTC, carusogabriel requested changes

2019-02-09 15:13 UTC, carusogabriel commented on ext/spl/tests/bug68004.phpt
> +--XFAIL--
We won't accept `XFAIL` tests :confused:

2019-02-11 21:01 UTC, petk commented
Hello, thank you for the pull request. The XFAIL tests for the PHP-7.4 and master branches should instead go one step further and try to fix the bug if possible. The XFAIL tests are not being merged to the php-src repository anymore. Thanks and sorry for inconvenience.

2019-02-11 21:01 UTC, closed without merging