Test the function readline with null parameter
phpcommunity/phptestfest-php-src pull request #93
Opened 2017-11-07 23:41 UTC by royopa

Test the function readline with null parameter (wrong because the function expects a string parameter).
User Group: PHPSP #phptestfestbrasil
http://phpsp.org.br/

2017-11-08 06:05 UTC, krakjoe requested changes

2017-11-08 06:05 UTC, krakjoe commented on ext/readline/tests/readline_nullparam.phpt
> +$line = readline(null);
This would be an unnecessary test of ZPP ... and it seems incomplete anyway ...

2017-11-09 07:11 UTC, krakjoe commented on ext/readline/tests/readline_nullparam.phpt
> +Warning: readline() expects parameter 1 to be string, null given in %s on line %d
This is an unnecessary test of ZPP.

2019-02-17 19:00 UTC, petk commented
Hello, thank you for the pull request. As mentioned above, the ZPP tests aren't being merge to the upstream anymore because they test redundant things. See this discussion for more info at https://externals.io/message/103886

Closing this one as resolved. 👍

2019-02-17 19:00 UTC, closed without merging